export const cheapest = () => ({ type: 'CHEAPEST' });
export const fast = () => ({ type: 'FAST' });
export const optimal = () => ({ type: 'OPTIMAL' });
export const all = () => ({ type: 'ALL' });
export const off = () => ({ type: 'OFF' });
export const noTransfers = () => ({ type: 'NOTRANSFERS' });
export const oneTransfers = () => ({ type: 'ONETRANSFERS' });
export const twoTransfers = () => ({ type: 'TWOTRANSFERS' });
export const threeTransfers = () => ({ type: 'THREETRANSFERS' });
